# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: chmod +x mvnw && ./mvnw clean verify
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
