# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Copy_Infra_Files
  displayName: Copy Infra Files
  jobs:
    - job: Copy_Files_and_Publish
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'infra'
            Contents: '*.json'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'infra'
            publishLocation: 'Container'

- stage: Build_Application
  displayName: Build Application
  jobs:

  - job: Build_application_and_Push
    steps:
      
      - script: chmod +x mvnw && ./mvnw clean verify
        displayName: 'Build Application'

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'target'
          Contents: '*'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: Docker@2
        displayName: 'Build Image'
        inputs:
          containerRegistry: 'acr-assgnapp-sc'
          repository: 'assignmentappACR'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'