#Build pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

#Copy infra files for linked artifacts
- stage: Copy_Infra_Files
  displayName: Copy Infra Files
  jobs:
    - job: Copy_Files_and_Publish
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'infra'
            Contents: '*.json'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'infra'
            publishLocation: 'Container'
#Build docker image & push to acr
- stage: Build_Application
  displayName: Build Application
  jobs:

  - job: Build_application_and_Push
    steps:
      
      - script: chmod +x mvnw && ./mvnw clean verify
        displayName: 'Build Application'

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'target'
          Contents: '*'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: Docker@2
        displayName: 'Build Image'
        inputs:
          containerRegistry: 'acr-assgnapp-sc'
          repository: 'assignmentappACR'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(Build.BuildId)'
